services:
  # image project
  app:
    build:
      args:
        user: hypnoUser
        uid: 1000
      context: .
      dockerfile: Dockerfile
    tty: true
    container_name: hypno-app
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www
    depends_on:
      - redis
    networks:
      - laravel

  # nginx
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8989:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel

  # db mysql
  db:
    image: mysql:8.0
    restart: unless-stopped
    container_name: hypno-db
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_HOST: '${DB_HOST}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

  redis:
    image: redis:latest
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
    driver: local
